# Generated by Django 3.0.6 on 2020-05-23 06:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airlines',
            fields=[
                ('Airline_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('afrom', models.CharField(max_length=15)),
                ('ato', models.CharField(max_length=15)),
                ('time', models.DateField(default=datetime.datetime(2020, 5, 23, 6, 43, 48, 305851, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='bookticket',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('User_id', models.CharField(max_length=12)),
                ('Airline_id', models.CharField(max_length=5)),
                ('issue_date', models.DateField(default=datetime.datetime(2020, 5, 23, 6, 43, 48, 357720, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('phone_no', models.BigIntegerField(unique=True)),
            ],
        ),
    ]
